---
- name: Setup NYC Records Proxy
  include_tasks: setup_proxy.yml
  when: setup_proxy

- name: Change timezone to "{{ local_timezone }}"
  timezone:
    name: "{{ local_timezone }}"

- name: Setup NYCRecords SSH Keys (Github)
  authorized_key:
    user: "{{ item.0.system_user }}"
    key: "https://github.com/{{ item.1 }}.keys"
  with_subelements:
    - "{{ ssh_users }}"
    - github_users

- name: Set Hostname  # noqa 301 305
  shell:
    cmd: "hostnamectl set-hostname {{ inventory_hostname_short }}"

- name: Install Common Packages
  include_tasks: install_common_packages.yml

- name: Setup Security Requirements
  include_tasks: setup_security.yml

- name: Start sysstat on boot
  systemd:
    name: sysstat
    enabled: yes
    daemon_reload: yes
    state: started

- name: Setup Storage Device Mounts
  include_tasks: setup_mount_points.yml
  when: setup_mount_points

- name: Setup HTTPS for Nginx
  include_tasks: setup_https.yml
  when: setup_https
