---
- name: Insert proxy profile configuration
  template:
    src: templates/proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    mode: 0644

- name: Setup proxy for sudo
  template:
    src: files/proxy.j2
    dest: /etc/sudoers.d/proxy
    mode: 0644
