---
- name: Install python and pip and packages
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ python_package_name }}"
    - "{{ python_package_name }}-pip"


- name: Ensure python OpenSSL dependencies are installed.
  pip:
    name: ['pyOpenssl', 'cryptography']
    state: present
    virtualenv: /tmp/https_setup
    virtualenv_site_packages: yes
    virtualenv_command: "{{ python_executable }} -m venv"
  environment:
    http_proxy: "{{ http_proxy_protocol}}://{{ http_proxy_username}}:{{ http_proxy_password }}@{{ http_proxy_hostname }}:{{ http_proxy_port }}"
    https_proxy: "{{ http_proxy_protocol}}://{{ http_proxy_username}}:{{ http_proxy_password }}@{{ http_proxy_hostname }}:{{ http_proxy_port }}"
