--- 
- name: Ensure Directories Exist for SSL
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/letsencrypt/live/
    - /etc/ssl/private/
    - /etc/letsencrypt/live/{{ server_hostname }}/

- name: Determine if private key exists
  stat:
    - path: /etc/letsencrypt/live/{{ server_hostname }}/privkey.pem
  register: private_key

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/letsencrypt/live/{{ server_hostname }}/privkey.pem
  when: not private_key.stat.exists

- name: Determine if CSR Exists
  stat:
    - path: /etc/ssl/private/{{ server_hostname }}.csr
  register: csr

- name: Generate an CSR
  openssl_csr:
    country_name: "US"
    state_or_province_name: "NY"
    locality_name: "New York"
    organization_name: "Department of Records and Information Services"
    organizational_unit_name: "IT - Application Development"
    email_address: "{{ server_admin_email }}"
    common_name: "{{ server_hostname }}"
    use_common_name_for_san: yes
    path: /etc/ssl/private/{{ server_hostname }}.csr
    privatekey_path: /etc/letsencrypt/live/{{ server_hostname }}/privkey.pem
  when: not csr.stat.exists

- name: Determine if certificate exists
  stat:
    - path: /etc/ssl/private/{{ server_hostname }}/fullchain.pem
  register: certificate

- name: Generate a Self Signed OpenSSL certificate for Web Server.
  openssl_certificate:
    path: /etc/letsencrypt/live/{{ server_hostname }}/fullchain.pem
    privatekey_path: /etc/letsencrypt/live/{{ server_hostname }}/privkey.pem
    csr_path: /etc/ssl/private/{{ server_hostname }}.csr
    provider: selfsigned
  when: not certificate.stat.exists

- name: Determine if DH Parameters exist
  stat:
    path: /etc/ssl/dhparams.pem
  register: dhparams

- name: Generate DH parameters
  openssl_dhparam:
    path: /etc/ssl/dhparams.pem 
    size: 1024
  when: not dhparams.stat.exists
  
- name: Download CSR
  fetch:
    src: /etc/ssl/private/{{ server_hostname }}.csr
    dest: files/https/{{ server_hostname }}/
