---
- name: Install python and pip and packages
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ python_executable }}"
    - "{{ python_executable }}-pip"


- name: Ensure python OpenSSL dependencies are installed.
  pip:
    name: ['pyOpenssl', 'cryptography']
    state: present
    virtualenv: /tmp/https_setup
    virtualenv_site_packages: yes
    virtualenv_command: "{{ python_executable }} -m venv"
