---
# tasks file for nycrecords_role_common
- name: Insert proxy profile configuration
  template:
    src: templates/proxy.sh.j2
    dest: /etc/profile.d/proxy.sh

- name: Setup proxy for sudo
  template:
    src: files/proxy.j2
    dest: /etc/sudoers.d/proxy
