---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: rhsm
    rhsm_username: "{{ lookup('env', 'RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'RHSM_PASSWORD') }}"
    rhsm_auto_attach: true
    rhsm_server_proxy_hostname: "{{ lookup('env', 'http_proxy_hostname') }}"
    rhsm_server_proxy_port: "{{ lookup('env', 'http_proxy_port') }}"
    rhsm_server_proxy_user: "{{ lookup('env', 'http_proxy_user') }}"
    rhsm_server_proxy_password: "{{ lookup('env', 'http_proxy_password') }}"
    rhsm_consumer_name: "nycrecords_{{ '%Y%m%d_%H%M%s' | strftime(ansible_date_time.epoch) }}"

    # Role: Common
    setup_mount_points: false
    setup_proxy: false
    setup_https: false

  roles:
    - role: nycrecords.rhsm
      tags:
        - always
    - role: ansible-role-consul
